[package]
name = "rwinrepl"
version = "0.1.0"
authors = ["chin0 <kafuuchin0>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystone = "0.9.0"
windows = "0.8"
bindings = {path = "bindings"}
ctrlc = "3.1.9"

